# Required
version: 2


build:
  os: ubuntu-24.04
  tools:
    python: "3.12"


# install local package before executing anything
# the [readthedocs] extra is used to install the required dependencies
python:
  install:
    - method: pip
      path: ".[readthedocs]"
